query($pageIndex: Int, $pageSize: Int, $orderBy: String, $orderByType: String, $code: String, $name: String, $familyId: Int, $modelNames: [String], $partNoNames: [String] ){
  apparatusDefs(pageIndex: $pageIndex, pageSize: $pageSize, orderBy: $orderBy, orderByType: $orderByType, code: $code, name: $name, familyId: $familyId, modelNames: $modelNames, partNoNames: $partNoNames) {
    payload {
      id
      code
      recBy
      uPL
      name
      owner
      recOn
      family {
        id
        name
      }
      usedFor
      models
      partNos
      pMPeriod
      remark
      workcell {
        id
        name
      }
    }
    totalCount
  }
}
