query($pageIndex: Int, $pageSize: Int, $orderBy: String, $orderByType: String, $status: String, $billNo: String, $location: String, $defId: Int, $modelNames: [String], $partNoNames: [String]){
  apparatusEntities(pageIndex: $pageIndex, pageSize: $pageSize, orderBy: $orderBy, orderByType: $orderByType, billNo: $billNo, status: $status, location: $location, defId: $defId,models: $modelNames, partNos: $partNoNames ) {
    payload {
      id
      billNo
      defId
      def {
        id
        code
        recBy
        uPL
        name
        owner
        recOn

        familyId
        family {
          name
        }

        models
        partNos
        pMPeriod
        remark

      }
      seqId
      status
      location
      picture
      regDate
      status
    }
    totalCount
  }
}
