query($pageIndex: Int, $pageSize: Int, $orderBy: String, $orderByType: String, $status: String, $billNo: String, $location: String, $defId: Int){
  apparatusEntities(pageIndex: $pageIndex, pageSize: $pageSize, orderBy: $orderBy, orderByType: $orderByType, billNo: $billNo, status: $status, location: $location, defId: $defId) {
    payload {
      id
      billNo
      defId
      def {
        id
        code
        recBy
        uPL
        name
        owner
        recOn

        models
        partNos
        pMPeriod
        remark

      }
      seqId
      status
      location
      picture
      regDate
      status
    }
    totalCount
  }
}
