query ($pageIndex: Int, $pageSize: Int, $orderBy: String, $orderByType: String){
  families(pageIndex: $pageIndex, pageSize: $pageSize, orderBy: $orderBy, orderByType: $orderByType) {
    payload {
      id
      name
    }
    totalCount
  }
}
