query($pageIndex: Int, $pageSize: Int, $orderBy: String, $orderByType: String, $outRecordPerson: String, $inRecordPerson: String, $outHandlingPerson: String,  $inHandlingPerson: String, $apparatusEntityId: Int, $lineId: Int, $outTimeFrom: DateTime, $outTimeTo: DateTime, $inTimeFrom: DateTime, $inTimeTo: DateTime){
  ioRecords(pageIndex: $pageIndex, pageSize: $pageSize, orderBy: $orderBy, orderByType: $orderByType, outRecordPerson: $outRecordPerson, inRecordPerson: $inRecordPerson, outHandlingPerson: $outHandlingPerson, inHandlingPerson: $inHandlingPerson, apparatusEntityId: $apparatusEntityId, lineId: $lineId, outTimeFrom: $outTimeFrom, outTimeTo: $outTimeTo, inTimeFrom: $inTimeFrom, inTimeTo: $inTimeTo) {
    payload {
      id
      apparatusEntity {
        billNo
        def {
          family {
            name
          }
          name
          code
          familyId
          models
          partNos
        }
        defId
        location
        regDate
        seqId
        status
        picture

      }
      apparatusEntityId
      inHandlingPerson
      inRecordPerson
      inTime
      line {
        name
      }
      lineId
      outHandlingPerson
      outRecordPerson
      outTime

    }
    totalCount
  }
}

