query($pageIndex: Int, $pageSize: Int, $orderBy: String, $orderByType: String, $familyId: Int, $name: String){
  models(pageIndex: $pageIndex, pageSize: $pageSize, orderBy: $orderBy, orderByType: $orderByType, familyId: $familyId, name: $name) {
    payload {
      id
      name
      family {
        id
        name
      }
      familyId
    }
    totalCount
  }
}
