query($pageIndex: Int, $pageSize: Int, $orderBy: String, $orderByType: String, $modelId: Int){
  partNos(pageIndex: $pageIndex, pageSize: $pageSize, orderBy: $orderBy, orderByType: $orderByType, modelId: $modelId) {
    payload {
      id
      name
      model {
        id
        name
      }
      modelId
    }
    totalCount
  }
}
