query($pageIndex: Int, $pageSize: Int, $orderBy: String, $orderByType: String, $name: String){
  partNos(pageIndex: $pageIndex, pageSize: $pageSize, orderBy: $orderBy, orderByType: $orderByType, name: $name) {
    payload {
      id
      name
    }
    totalCount
  }
}
