query($pageIndex: Int, $pageSize: Int, $orderBy: String, $orderByType: String $applicationTimeFrom: DateTime, $applicationTimeTo: DateTime){
  repairRecords(pageIndex: $pageIndex, pageSize: $pageSize, orderBy: $orderBy, orderByType: $orderByType, applicationTimeTo: $applicationTimeTo, applicationTimeFrom: $applicationTimeFrom) {
    payload {
      acceptor
      acceptorTime
      apparatusEntity {
        seqId
        def {
          code
        }
      }
      apparatusEntityId
      applicationTime
      description
      finishTime
      id
      picture
      proposer
      status
    }
    totalCount
  }
}
