query($pageIndex: Int){
  repairRecords(pageIndex: $pageIndex) {
    payload {
      acceptor
      acceptorTime
      apparatusEntity {
        id
        seqId
        def {
          code
        }
      }
      apparatusEntityId
      applicationTime
      description
      finishTime
      id
      picture
      proposer
      status
    }
    totalCount
  }
}
