query($pageIndex: Int){
  scrapRecords(pageIndex: $pageIndex) {
    payload {
      apparatusEntity {
        seqId
        def {
          code
        }
      }
      apparatusEntityId
      proposer
      applicationTime
      middleProcessor
      finalProcessor
      id
      proposer
      status
      reason
    }
    totalCount
  }
}
