query($pageIndex: Int, $pageSize: Int, $orderBy: String, $orderByType: String, $applicationTimeFrom: DateTime, $applicationTimeTo: DateTime, $apparatusEntityId: Int, $status: String, $proposer: String, $middleProcessor: String, $middleProcessTimeFrom: DateTime, $middleProcessTimeTo: DateTime, $finalProcessTimeFrom: DateTime, $finalProcessTimeTo: DateTime, $finalProcessor: String){
  scrapRecords(pageIndex: $pageIndex, pageSize: $pageSize, orderBy: $orderBy, orderByType: $orderByType, applicationTimeFrom: $applicationTimeFrom, applicationTimeTo: $applicationTimeTo, apparatusEntityId: $apparatusEntityId, status: $status, proposer: $proposer, middleProcessor: $middleProcessor, middleProcessTimeFrom: $middleProcessTimeFrom, middleProcessTimeTo: $middleProcessTimeTo, finalProcessTimeFrom: $finalProcessTimeFrom, finalProcessTimeTo: $finalProcessTimeTo, finalProcessor: $finalProcessor) {
    payload {
      apparatusEntity {
        seqId
        def {
          code
        }
      }
      apparatusEntityId
      proposer
      applicationTime
      middleProcessor
      middleProcessTime
      finalProcessor
      finalProcessTime
      id
      proposer
      status
      reason
    }
    totalCount
  }
}
