query($employeeId: String){
  users(employeeId: $employeeId) {
    payload {
      employeeId
      userType {
        id
        name
        permission
      }
      id
      workcell {
        name
        id
      }
      workcellId
    }

  }
}
