query($pageIndex: Int, $pageSize: Int, $orderBy: String, $orderByType: String, $employeeId: String, $userTypeId: Int, $workcellId: Int){
  users(pageIndex: $pageIndex, pageSize: $pageSize, orderBy: $orderBy, orderByType: $orderByType, employeeId: $employeeId, userTypeId: $userTypeId, workcellId: $workcellId) {
    payload {
      employeeId
      mail
      userType {
        id
        name
        permission
        permissions {
          name
          value
        }
      }
      id
      workcell {
        name
        id
      }
      workcellId
    }

  }
}
