query($employeeId: String){
  users(employeeId: $employeeId) {
    payload {
      employeeId
      mail
      userType {
        id
        name
        permission
        permissions {
          name
          value
        }
      }
      id
      workcell {
        name
        id
      }
      workcellId
    }

  }
}
