query ($pageIndex: Int, $pageSize: Int, $orderBy: String, $orderByType: String) {
  workcells(pageIndex: $pageIndex, pageSize: $pageSize, orderBy: $orderBy, orderByType: $orderByType) {
    totalCount
    payload {
      id
      name
    }
  }
}
