query($id: Int!){
  scrapRecord(id: $id) {
    apparatusEntity {
      seqId
      def {
        name
        code
      }
    }
    apparatusEntityId
    proposer
    applicationTime
    middleProcessor
    middleProcessTime
    finalProcessor
    finalProcessTime
    id
    proposer
    status
    reason
  }
}
