query($workcellId: Int!) {
  systemSetting(workcellId: $workcellId) {
      id
      ioInWaste
      ioOutWaste
      repairWaste
      predictSchedule
      checkRemindSchedule
      trainSchedule
  }
}
